// Reads the 5 bot snapshots and writes kahuna/bots.js —
// a self-contained JS file with classifier data + LCS runtime
// for use in the browser game.

'use strict';

const fs = require('fs');

const BOTS = [
  { file: 'bots/bot_04000.json', id: 'rangi',  name: 'Rangi',  title: 'The Bridge Builder',  desc: 'Methodical but naive — lays bridges everywhere, phase-blind.' },
  { file: 'bots/bot_08000.json', id: 'nalu',   name: 'Nalu',   title: 'The Settler',          desc: 'Patient and hub-hungry. Flows toward high-degree islands, rarely removes.' },
  { file: 'bots/bot_12000.json', id: 'koa',    name: 'Koa',    title: 'The Warrior',          desc: 'Aggressive. Removes bridges, targets hubs, exploits a lead ruthlessly.' },
  { file: 'bots/bot_16000.json', id: 'hiku',   name: 'Hiku',   title: 'The Specialist',       desc: 'Hyper-focused on Phase 1. Locks down hub islands before you know it.' },
  { file: 'bots/bot_20000.json', id: 'mano',   name: 'Mano',   title: 'The Shark',            desc: 'Endgame predator. Targets what you own, knows how to fight from behind.' },
];

const TOP_N = 80; // classifiers per bot to embed

const botData = BOTS.map(b => {
  const raw = JSON.parse(fs.readFileSync(b.file, 'utf8'));
  raw.sort((a, x) => x.strength - a.strength);
  const clfs = raw.slice(0, TOP_N).map(c => [c.condition, +c.strength.toFixed(3)]);
  return { ...b, clfs };
});

const out = `// Auto-generated by lcs/export-bots.js — do not edit by hand.
// Contains classifier populations for 5 trained LCS bots + matching runtime.

const LCS_BOTS = ${JSON.stringify(botData.map(b => ({
  id: b.id, name: b.name, title: b.title, desc: b.desc, clfs: b.clfs
})), null, 2)};

// ---- LCS runtime (browser) ----
// Mirrors lcs.js encode/match logic but reads from the game's global state.

const LCS_BITS = 20;
const LCS_SPEC_WEIGHT = 0.5;

function lcsProgressBits(myBr, majNeeded) {
  if (myBr === 0) return '00';
  if (myBr >= majNeeded) return '11';
  if (myBr === majNeeded - 1) return '10';
  return '01';
}

function lcsWouldCascade(ci, p) {
  const opp = 1 - p;
  for (const isl of CONNS[ci]) {
    let mine = 0, oppCnt = 0;
    CONNS.forEach(([a, b], c2) => {
      if (a !== isl && b !== isl) return;
      const br = c2 === ci ? p : bridges[c2];
      if (br === p) mine++; else if (br === opp) oppCnt++;
    });
    if (mine >= MAJ[isl] && oppCnt > 0) return true;
  }
  return false;
}

function lcsRemovalDisrupts(ci, p) {
  const opp = 1 - p;
  for (const isl of CONNS[ci]) {
    if (controlled[isl] !== opp) continue;
    let oppAfter = 0;
    CONNS.forEach(([a, b], c2) => {
      if (a !== isl && b !== isl) return;
      const br = c2 === ci ? null : bridges[c2];
      if (br === opp) oppAfter++;
    });
    if (oppAfter < MAJ[isl]) return true;
  }
  return false;
}

function lcsEncode(move) {
  const p = curP, opp = 1 - p;
  const [A, B] = CONNS[move.ci];
  const isRem = move.type === 'remove' ? '1' : '0';

  let myBrA = 0, oppBrA = 0;
  CONNS.forEach(([a, b], ci) => {
    if (a !== A && b !== A) return;
    const br = ci === move.ci ? (move.type === 'place' ? p : null) : bridges[ci];
    if (br === p) myBrA++; else if (br === opp) oppBrA++;
  });

  let myBrB = 0, oppBrB = 0;
  CONNS.forEach(([a, b], ci) => {
    if (a !== B && b !== B) return;
    const br = ci === move.ci ? (move.type === 'place' ? p : null) : bridges[ci];
    if (br === p) myBrB++; else if (br === opp) oppBrB++;
  });

  const cascA = move.type === 'place'
    ? (lcsWouldCascade(move.ci, p) && CONNS[move.ci].includes(A) ? '1' : '0')
    : (lcsRemovalDisrupts(move.ci, p) && CONNS[move.ci].includes(A) ? '1' : '0');
  const cascB = move.type === 'place'
    ? (lcsWouldCascade(move.ci, p) && CONNS[move.ci].includes(B) ? '1' : '0')
    : (lcsRemovalDisrupts(move.ci, p) && CONNS[move.ci].includes(B) ? '1' : '0');

  const phase = gamePhase === 1 ? '01' : gamePhase === 2 ? '10' : '11';
  const sd = scores[p] - scores[opp];
  const behind = sd < 0 ? '1' : '0';
  const ahead  = sd > 0 ? '1' : '0';
  const hubA = DEG[A] >= 4 ? '1' : '0';
  const hubB = DEG[B] >= 4 ? '1' : '0';
  const handSize = hands[p].length - (move.type === 'place' ? 1 : 2);
  const thin = handSize <= 2 ? '1' : '0';

  return isRem +
    lcsProgressBits(myBrA, MAJ[A]) + lcsProgressBits(oppBrA, MAJ[A]) +
    (controlled[A] === opp ? '1' : '0') + cascA +
    lcsProgressBits(myBrB, MAJ[B]) + lcsProgressBits(oppBrB, MAJ[B]) +
    (controlled[B] === opp ? '1' : '0') + cascB +
    phase + behind + ahead + hubA + hubB + thin;
}

function lcsMatches(cond, feat) {
  for (let i = 0; i < LCS_BITS; i++)
    if (cond[i] !== '#' && cond[i] !== feat[i]) return false;
  return true;
}

function lcsScoreMove(feat, clfs) {
  let total = 0;
  for (const [cond, strength] of clfs) {
    if (lcsMatches(cond, feat)) {
      let spec = 0;
      for (let i = 0; i < LCS_BITS; i++) if (cond[i] !== '#') spec++;
      total += strength * (1 + LCS_SPEC_WEIGHT * spec / LCS_BITS);
    }
  }
  return total;
}

// Returns the best play move (place or remove) for the current player
// using the given classifier array.
function lcsFindBestMove(clfs) {
  const p = curP, opp = 1 - p;
  let best = -Infinity, bm = null;

  // place moves
  hands[p].forEach((isl, hi) => {
    CONNS.forEach(([a, b], ci) => {
      if ((a !== isl && b !== isl) || bridges[ci] !== null) return;
      const feat = lcsEncode({ type: 'place', ci });
      const sc = lcsScoreMove(feat, clfs);
      if (sc > best) { best = sc; bm = { type: 'place', h: hi, ci }; }
    });
  });

  // remove moves
  for (let i = 0; i < hands[p].length; i++) {
    for (let j = i + 1; j < hands[p].length; j++) {
      const i1 = hands[p][i], i2 = hands[p][j];
      CONNS.forEach(([a, b], ci) => {
        if (bridges[ci] !== opp) return;
        if (!((i1 === a || i1 === b) && (i2 === a || i2 === b))) return;
        const feat = lcsEncode({ type: 'remove', ci });
        const sc = lcsScoreMove(feat, clfs) + 3; // small remove bonus
        if (sc > best) { best = sc; bm = { type: 'remove', h1: i, h2: j, ci }; }
      });
    }
  }

  return bm;
}
`;

const path = require('path');
fs.writeFileSync(path.join(__dirname, '../kahuna/bots.js'), out);
console.log('Wrote kahuna/bots.js');
console.log('Bots:', botData.map(b => `${b.name} (${b.clfs.length} classifiers, top strength ${b.clfs[0][1]})`).join(', '));
